sonar.projectKey=envoyage
sonar.projectName=Envoyage
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=coverage.out,envoyage
sonar.go.coverage.reportPaths=coverage.out
