package ageenv

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"strings"

	"filippo.io/age"
	"github.com/swoogi/envoyage/internal/dotenv"
)

type DecryptOptions struct {
	InputPath      string
	OutputPath     string
	IdentityPath   string
	ForceOverwrite bool
}

// Decrypt decrypts age-encrypted dotenv data entirely in memory.
func Decrypt(ciphertext []byte, identityPath string) (map[string]string, error) {
	plaintext, err := DecryptBytes(ciphertext, identityPath)
	if err != nil {
		return nil, err
	}

	env, err := dotenv.Parse(bytes.NewReader(plaintext))
	if err != nil {
		return nil, fmt.Errorf("parse decrypted env file: %w", err)
	}
	return env, nil
}

// DecryptBytes decrypts age-encrypted data entirely in memory.
func DecryptBytes(ciphertext []byte, identityPath string) ([]byte, error) {
	identities, err := loadIdentities(identityPath)
	if err != nil {
		return nil, err
	}

	reader, err := age.Decrypt(bytes.NewReader(ciphertext), identities...)
	if err != nil {
		return nil, fmt.Errorf("decrypt age env file: %w%s", err, decryptHint(identityPath))
	}

	plaintext, err := io.ReadAll(reader)
	if err != nil {
		return nil, fmt.Errorf("read decrypted env file: %w", err)
	}
	return plaintext, nil
}

// DecryptFile decrypts an age-encrypted file to a plaintext file.
func DecryptFile(opts DecryptOptions) error {
	if opts.InputPath == "" {
		return fmt.Errorf("--in is required\n\nhint:\n  pass --in .env.age or place the encrypted env file at .env.age")
	}
	if opts.OutputPath == "" {
		return fmt.Errorf("--out is required\n\nhint:\n  pass --out .secrets.env to choose where plaintext secrets are written")
	}

	ciphertext, err := os.ReadFile(opts.InputPath)
	if err != nil {
		return fmt.Errorf("read encrypted env file %s: %w\n\nhint:\n  create it with: envoyage encrypt\n  or pass --in PATH to select a different encrypted env file", opts.InputPath, err)
	}

	plaintext, err := DecryptBytes(ciphertext, opts.IdentityPath)
	if err != nil {
		return err
	}

	flag := os.O_WRONLY | os.O_CREATE | os.O_TRUNC
	if !opts.ForceOverwrite {
		flag = os.O_WRONLY | os.O_CREATE | os.O_EXCL
	}
	file, err := os.OpenFile(opts.OutputPath, flag, 0o600)
	if err != nil {
		return fmt.Errorf("create decrypted env file %s: %w\n\nhint:\n  pass --force to overwrite an existing file\n  or pass --out PATH to choose another output path", opts.OutputPath, err)
	}
	defer file.Close()

	if _, err := io.Copy(file, bytes.NewReader(plaintext)); err != nil {
		return fmt.Errorf("write decrypted env file %s: %w", opts.OutputPath, err)
	}
	return nil
}

func loadIdentities(path string) ([]age.Identity, error) {
	if path == "" {
		return nil, fmt.Errorf("identity file required%s", identityHint())
	}

	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read identity file %s: %w%s", path, err, identityHint())
	}

	ids, err := age.ParseIdentities(strings.NewReader(string(data)))
	if err != nil {
		return nil, fmt.Errorf("parse identity file %s: %w\n\nhint:\n  make sure this file was generated by envoyage keygen or age-keygen\n  then retry with --identity %s", path, err, path)
	}
	return ids, nil
}

func identityHint() string {
	return "\n\nhint:\n  pass --identity /path/to/age-key.txt\n  or set AGE_IDENTITY_FILE=/path/to/age-key.txt\n  or create the default identity with: sudo envoyage keygen"
}

func decryptHint(identityPath string) string {
	if identityPath == "" {
		return identityHint()
	}
	return fmt.Sprintf("\n\nhint:\n  check that %s is the identity matching the recipient used for encryption\n  inspect or recreate the encrypted file with: envoyage encrypt --identity %s", identityPath, identityPath)
}
