services:
  minio:
    image: minio/minio:latest
    container_name: envoyage-minio
    command: server /data --console-address ":9001"
    ports:
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL}
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - minio-data:/data

volumes:
  minio-data:
